// <auto-generated />
namespace Lessons_Cordinator_beta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MIG1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MIG1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007272155505_MIG1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
